Controllers/OgrencilerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using OgrenciNotMvc.Models.EntityFramework;


namespace OgrenciNotMvc.Controllers
{
    public class OgrencilerController : Controller
    {



        DbMvcOkulEntities db = new DbMvcOkulEntities();

        // GET: Ogrenciler
        public ActionResult Index()
        {

            var ogrenciler = db.TBLOGRENCI.ToList();
            return View(ogrenciler);
        }

        [HttpGet]
        public ActionResult OgrenciEkle()
        {

            List<SelectListItem> degerler = (from i in db.TBLKULUPLER.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.KULUPAD,
                                                 Value = i.KULUPID.ToString()
                                             }
                                                 ).ToList();

            ViewBag.dgr = degerler;


            List<SelectListItem> cinsiyet = (from i in db.TBLOGRENCI.ToList()

                                             select new SelectListItem
                                             {
                                                 Text = i.OGRCINSIYET,
                                                 Value = i.OGRCINSIYET.ToString()
                                             }
                                             ).ToList();

            ViewBag.cns = cinsiyet;


            return View();
        }

        [HttpPost]
        public ActionResult OgrenciEkle(TBLOGRENCI p)
        {

            var klp = db.TBLKULUPLER.Where(m => m.KULUPID == p.TBLKULUPLER.KULUPID).FirstOrDefault();
            db.TBLOGRENCI.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Sil(int id)
        {

            var ogrenci = db.TBLOGRENCI.Find(id);
            db.TBLOGRENCI.Remove(ogrenci);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult OgrenciGetir(int id)
        {

            var ogrenciler = db.TBLOGRENCI.Find(id);
            return View("OgrenciGetir", ogrenciler);
        }

        public ActionResult Guncelle(TBLOGRENCI p)
        {

            var ogrenciler = db.TBLOGRENCI.Find(p.OGRENCIID);
            ogrenciler.OGRAD = p.OGRAD;
            ogrenciler.OGRSOYAD = p.OGRSOYAD;
            ogrenciler.OGRFOTO = p.OGRFOTO;
            ogrenciler.OGRCINSIYET = p.OGRCINSIYET;
            ogrenciler.OGRKULUP = p.OGRKULUP;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

       
    }
}

Views/Ogrenciler/Index.cshtml
@using OgrenciNotMvc.Models.EntityFramework;
@model List<TBLOGRENCI>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table table-bordered">

    <tr>
        <th>ÖĞRENCİ ID</th>
        <th>ÖĞRENCİ ADI</th>
        <th>ÖĞRENCİ SOYADI</th>
        <th>ÖĞRENCİ FOTOĞRAFI</th>
        <th>ÖĞRENCİ CİNSİYETİ</th>
        <th>ÖĞRENCİ KULUP</th>
        <th>İŞLEMLER</th>
    </tr>



    <tbody>

        @foreach(var ogrenciler in Model)
        {
            <tr>
                <td>@ogrenciler.OGRENCIID</td>
                <td>@ogrenciler.OGRAD</td>
                <td>@ogrenciler.OGRSOYAD</td>
                <td>@ogrenciler.OGRFOTO</td>
                <td>@ogrenciler.OGRCINSIYET</td>
                <td>@ogrenciler.OGRKULUP</td>
                <td><a href="/Ogrenciler/Sil/@ogrenciler.OGRENCIID" class="btn btn-danger">Sil</a>
                <a href="/Ogrenciler/OgrenciGetir/@ogrenciler.OGRENCIID" class="btn btn-success">Güncelle</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<a href="/Ogrenciler/OgrenciEkle" class="btn btn-primary">Yeni Öğrenci Ekle</a>

Views/Ogrenciler/OgrenciEkle.cshtml
@model OgrenciNotMvc.Models.EntityFramework.TBLOGRENCI
@{
    ViewBag.Title = "OgrenciEkle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


    <form method="post" name="form-group">

        <div>
            <label>Öğrenci Adı</label>
            <input type="text" class="form-control" name="OGRAD" />
        </div>

        <div style="margin-top:10px">

            <label>Öğrenci Soyadı</label>
            <input type="text" class="form-control" name="OGRSOYAD" />
        </div>
        <div style="margin-top:10px">

            <label>Öğrenci Fotoğrafı</label>
            <input type="text" class="form-control" name="OGRFOTO" />
        </div>
        <div style="margin-top:10px">

            <label>Öğrenci Cinsiyeti</label>
            <input type="text" class="form-control" name="OGRCINSIYET" />
        </div>
        <div style="margin-top:10px">

            <label>Öğrenci Kulübü</label>
            @Html.DropDownListFor(m=>m.TBLKULUPLER.KULUPID, (List<SelectListItem>)ViewBag.dgr,new { @class="form-control"})
            
        </div>




        <div style="margin-top:10px">

            <button class="btn btn-primary">Öğrenci Ekle</button>
        </div>
    </form>

Views/Ogrenciler/OgrenciGetir.cshtml
@model OgrenciNotMvc.Models.EntityFramework.TBLOGRENCI
@{
    ViewBag.Title = "OgrenciGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Ogrenciler", FormMethod.Post))
{



    <div class="form-group">

        @Html.LabelFor(m => m.OGRAD)
        @Html.TextBoxFor(m => m.OGRAD, new { @class = "form-control" })

    </div>

    <div class="form-group">

        @Html.LabelFor(m => m.OGRSOYAD)
        @Html.TextBoxFor(m => m.OGRSOYAD, new { @class = "form-control" })

    </div>


    <div class="form-group">

        @Html.LabelFor(m => m.OGRCINSIYET)
        @Html.TextBoxFor(m => m.OGRCINSIYET, new { @class = "form-control" })

    </div>

    <div class="form-group">

        @Html.LabelFor(m => m.OGRFOTO)
        @Html.TextBoxFor(m => m.OGRFOTO, new { @class = "form-control" })

    </div>

    <div class="form-group">

        @Html.LabelFor(m => m.OGRKULUP)
        @Html.TextBoxFor(m => m.OGRKULUP, new { @class = "form-control" })

    </div>

    @Html.HiddenFor(m => m.OGRENCIID)

    <div style="margin-top:10px">

        <button class="btn btn-info">Güncelle</button>
    </div>

}