Controllers/NotlarController.cs
using OgrenciNotMvc.Models;
using OgrenciNotMvc.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;



namespace OgrenciNotMvc.Controllers
{
    public class NotlarController : Controller
    {

        DbMvcOkulEntities db = new DbMvcOkulEntities();
        // GET: Notlar
        public ActionResult Index()
        {

            var notlar = db.TBLNOTLAR.ToList();
            return View(notlar);
        }
        

        [HttpGet]
        public ActionResult YeniNot()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniNot(TBLNOTLAR p)
        {

            db.TBLNOTLAR.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult NotGetir(int id)
        {
            var notlar = db.TBLNOTLAR.Find(id);
            return View("NotGetir", notlar);
        }


        [HttpPost]
        public ActionResult NotGetir(Islem isl,TBLNOTLAR p, int sinav1=0, int sinav2=0, int sinav3=0, int proje=0)
        {

            if(isl.islemler=="Hesapla")
            {
                double ortalama = (sinav1 + sinav2 + sinav3 + proje) / 4;
                ViewBag.ort = ortalama;
            }
            if(isl.islemler =="NotGuncelle")
            {
                var notlar = db.TBLNOTLAR.Find(p.NOTID);
                notlar.SINAV1 = p.SINAV1;
                notlar.SINAV2 = p.SINAV2;
                notlar.SINAV3 = p.SINAV3;
                notlar.PROJE = p.PROJE;
                notlar.ORTALAMA = p.ORTALAMA;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }
    }
}

Views/Notlar/Index.cshtml
@using OgrenciNotMvc.Models.EntityFramework;
@model List<TBLNOTLAR>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table table-bordered">

    <tr>
        <th>NOT ID</th>
        <th>DERS ID</th>
        <th>OGRENCI ID</th>
        <th>SINAV 1</th>
        <th>SINAV 2</th>
        <th>SINAV 3</th>
        <th>PROJE</th>
        <th>ORTALAMA</th>
        <th>DURUM</th>
        <th>GÜNCELLE</th>
    </tr>

    <tbody>

        @foreach(var notlar in Model)
        {
            <tr>
                <td>@notlar.NOTID</td>
                <td>@notlar.DERSID</td>
                <td>@notlar.OGRID</td>
                <td>@notlar.SINAV1</td>
                <td>@notlar.SINAV2</td>
                <td>@notlar.SINAV3</td>
                <td>@notlar.PROJE</td>
                <td>@notlar.ORTALAMA</td>
                <td>@notlar.DURUM</td>
                <td><a href="/Notlar/NotGetir/@notlar.NOTID" class="btn btn-success">Güncelle</a></td>

            </tr>
        }
    </tbody>

</table>

<a href="/Notlar/YeniNot" class="btn btn-primary">Yeni Not Girişi</a>

Views/Notlar/NotGetir.cshtml
@model OgrenciNotMvc.Models.EntityFramework.TBLNOTLAR
@{
    ViewBag.Title = "NotGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("NotGetir", "Notlar", FormMethod.Post))
{

    <div class="form-group">

        @Html.LabelFor(m => m.OGRID)
        @Html.TextBoxFor(m => m.OGRID, new { @class = "form-control" })

    </div>

    <div class="form-group">

        @Html.LabelFor(m => m.SINAV1)
        @Html.TextBoxFor(m => m.SINAV1, new { @class = "form-control" })

    </div>

    <div class="form-group">

        @Html.LabelFor(m => m.SINAV2)
        @Html.TextBoxFor(m => m.SINAV2, new { @class = "form-control" })

    </div>


    <div class="form-group">

        @Html.LabelFor(m => m.SINAV3)
        @Html.TextBoxFor(m => m.SINAV3, new { @class = "form-control" })

    </div>

    <div class="form-group">

        @Html.LabelFor(m => m.PROJE)
        @Html.TextBoxFor(m => m.PROJE, new { @class = "form-control" })

    </div>

    <div class="form-group">

        @Html.LabelFor(m => m.ORTALAMA)
        @Html.TextBoxFor(m => m.ORTALAMA, new {@Value=@ViewBag.ort , @class = "form-control" })
         
    </div>

    <div class="form-group">

        @Html.LabelFor(m => m.DURUM)
        @Html.TextBoxFor(m => m.DURUM, new { @class = "form-control" })

    </div>

    @Html.HiddenFor(m => m.NOTID)


        
    <div>


    <button type="submit" name="islemler" value="Hesapla" class="btn btn-info">Hesapla</button>





    <button type="submit" name="islemler" value="NotGuncelle" class="btn btn-danger"> Güncelle</button>


        
        
        </div>
}

Views/Notlar/YeniNot.cshtml
@{
    ViewBag.Title = "YeniNot";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <form method="post" name="form-group">

        <div>
            <label>Öğrenci ID</label>
            <input type="text" class="form-control" name="OGRID" />
        </div>

        <div style="margin-top:10px">

            <label>Ders Adı</label>
            <input type="text" class="form-control" name="DERSID" />
        </div>
        <div style="margin-top:10px">

            <label>Sınav 1</label>
            <input type="text" class="form-control" name="SINAV1" />
        </div>
        <div style="margin-top:10px">

            <label>Sınav 2</label>
            <input type="text" class="form-control" name="SINAV2" />
        </div>

        <div style="margin-top:10px">

            <label>Sınav 3</label>
            <input type="text" class="form-control" name="SINAV3" />
        </div>
        <div style="margin-top:10px">

            <label>Proje</label>
            <input type="text" class="form-control" name="PROJE" />
        </div>



        <div style="margin-top:10px">

            <label>Ortalama</label>
            <input type="text" class="form-control" name="ORTALAMA" />
        </div>



        <div style="margin-top:10px">

            <label>Durum</label>
            <input type="text" class="form-control" name="DURUM" />
        </div>

        <div style="margin-top:10px">

            <button class="btn btn-primary">Yeni Not Ekle</button>
        </div>
    </form>