Controllers/KuluplerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OgrenciNotMvc.Models.EntityFramework;

namespace OgrenciNotMvc.Controllers
{
    public class KuluplerController : Controller
    {


        DbMvcOkulEntities db = new DbMvcOkulEntities();
        // GET: Kulupler
        public ActionResult Index()
        {

            var kulupler = db.TBLKULUPLER.ToList();
            return View(kulupler);
        }

        [HttpGet]
        public ActionResult KulupEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult KulupEkle(TBLKULUPLER p)
        {

            
            db.TBLKULUPLER.Add(p);
            db.SaveChanges();
            return View();
        }

        public ActionResult Sil(int id)
        {

            var kulup = db.TBLKULUPLER.Find(id);
            db.TBLKULUPLER.Remove(kulup);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KulupGetir(int id)
        {

            var kulupler = db.TBLKULUPLER.Find(id);
            return View("KulupGetir",kulupler);
        }

        public ActionResult Guncelle(TBLKULUPLER p)
        {
            var kulupler = db.TBLKULUPLER.Find(p.KULUPID);
            kulupler.KULUPAD = p.KULUPAD;
            kulupler.KULUPKONTENJAN = p.KULUPKONTENJAN;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Kulupler/Index.cshtml
@using OgrenciNotMvc.Models.EntityFramework;
@model List<TBLKULUPLER>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<table class="table table-bordered">

    <tr>
        <th>KULUP ID</th>
        <th>KULUP ADI</th>
        <th>KULUP KONTENJANI</th>
        <th>İŞLEMLER</th>
    </tr>

    <tbody>
        @foreach (var kulupler in Model)
        {
            <tr>
                <td>@kulupler.KULUPID</td>
                <td>@kulupler.KULUPAD</td>
                <td>@kulupler.KULUPKONTENJAN</td>
                <td><a href="/Kulupler/Sil/@kulupler.KULUPID" class="btn btn-danger">Sil</a>
                <a href="/Kulupler/KulupGetir/@kulupler.KULUPID" class="btn btn-success">Güncelle</a>
                </td>
            </tr>
        }

        
    </tbody>
</table>


<a href="/Kulupler/KulupEkle" class="btn btn-primary">Kulüp Ekle</a>

Views/Kulupler/KulupEkle.cshtml
@{
    ViewBag.Title = "KulupEkle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<form method="post" name="form-group">

    <div>
        <label>Kulüp Adı</label>
        <input type="text" class="form-control" name="KULUPAD" />
        <label>Kulüp Kontejanı</label>
        <input type="text" class="form-control" name="KULUPKONTENJAN" />
    </div>


    <div style="margin-top:10px">
        <button class="btn btn-primary">Kulüp Ekle</button>
    </div>
</form>

Views/Kulupler/KulupGetir.cshtml
@model OgrenciNotMvc.Models.EntityFramework.TBLKULUPLER
@{
    ViewBag.Title = "KulupGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Kulupler", FormMethod.Post))
{


    <div class="form-group">

        @Html.LabelFor(m => m.KULUPAD)
        @Html.TextBoxFor(m => m.KULUPAD, new { @class = "form-control" })
    </div>

    <div class="form-group">

        @Html.LabelFor(m => m.KULUPKONTENJAN)
        @Html.TextBoxFor(m => m.KULUPKONTENJAN, new { @class = "form-control" })
    </div>

    @Html.HiddenFor(m => m.KULUPID)

    <div style="margin-top:10px">
        <button class="btn btn-info">Güncelle</button>
    </div>
}